flowchart LR
  ___["..."]
  Alg__CDCHTracks["Alg::CDCHTracks"]
  Alg__DCHCollection["Alg::DCHCollection"]
  Alg__DCHDigi2Collection["Alg::DCHDigi2Collection"]
  Alg__DCHDigi2SimLink["Alg::DCHDigi2SimLink"]
  Alg__DCHDigi2SimLinkCollection["Alg::DCHDigi2SimLinkCollection"]
  Alg__DCHDigiCollection["Alg::DCHDigiCollection"]
  Alg__DCHDigiSimLink["Alg::DCHDigiSimLink"]
  Alg__DCHDigiSimLinkCollection["Alg::DCHDigiSimLinkCollection"]
  Alg__DCHName["Alg::DCHName"]
  Alg__DCHSimHits["Alg::DCHSimHits"]
  Alg__DCH_DigiCollection["Alg::DCH_DigiCollection"]
  Alg__DCH_ID_Encoding["Alg::DCH_ID_Encoding"]
  Alg__DCH_name["Alg::DCH_name"]
  Alg__DCH_simhits["Alg::DCH_simhits"]
  Alg__DCH_v2["Alg::DCH_v2"]
  Alg__DCHdigi["Alg::DCHdigi"]
  Alg__DCHdigiConf["Alg::DCHdigiConf"]
  Alg__DCHdigi_v01["Alg::DCHdigi_v01"]
  Alg__DCHdigi_v02["Alg::DCHdigi_v02"]
  Alg__DchName["Alg::DchName"]
  Alg__DiagEveryNTracks["Alg::DiagEveryNTracks"]
  Alg__GGTF_tracking["Alg::GGTF_tracking"]
  Alg__Geant4SimpleTrackerAction["Alg::Geant4SimpleTrackerAction"]
  Alg__Geant4TestTrackAction["Alg::Geant4TestTrackAction"]
  Alg__Geant4TrackerWeightedAction["Alg::Geant4TrackerWeightedAction"]
  Alg__GenFit["Alg::GenFit"]
  Alg__GenFit2DCHFitter["Alg::GenFit2DCHFitter"]
  Alg__GenFit2DCHFitter_props["Alg::GenFit2DCHFitter_props"]
  Alg__GenFitFieldSvc["Alg::GenFitFieldSvc"]
  Alg__GenFitMaterialSvc["Alg::GenFitMaterialSvc"]
  Alg__GenFitTracks["Alg::GenFitTracks"]
  Alg__GenFitTracks_trackStates_["Alg::GenFitTracks_trackStates_"]
  Alg__GenFitTracks_trackStates_omega["Alg::GenFitTracks_trackStates_omega"]
  Alg__GenFitTracks_trackStates_phi["Alg::GenFitTracks_trackStates_phi"]
  Alg__GenFitTracks_trackStates_qOverP["Alg::GenFitTracks_trackStates_qOverP"]
  Alg__GenFitTracks_trackStates_tanLambda["Alg::GenFitTracks_trackStates_tanLambda"]
  Alg__GenFitTracks_trackStates_theta["Alg::GenFitTracks_trackStates_theta"]
  Alg__GenFitTracks_tracks_omega["Alg::GenFitTracks_tracks_omega"]
  Alg__GenFitTracks_tracks_qOverP["Alg::GenFitTracks_tracks_qOverP"]
  Alg__GenFitTracks_tracks_theta["Alg::GenFitTracks_tracks_theta"]
  Alg__HelixFitter["Alg::HelixFitter"]
  Alg__InputTracks["Alg::InputTracks"]
  Alg__MinFittedPointsWithFI["Alg::MinFittedPointsWithFI"]
  Alg__MinHitsPerTrack["Alg::MinHitsPerTrack"]
  Alg__MinMeasurementsToFit["Alg::MinMeasurementsToFit"]
  Alg__OutputTracks["Alg::OutputTracks"]
  Alg__OutputTracksGGTF["Alg::OutputTracksGGTF"]
  Alg__PreFitOutlierVeto["Alg::PreFitOutlierVeto"]
  Alg__RetryIfNoFitterInfo["Alg::RetryIfNoFitterInfo"]
  Alg__SimpleFitDCHFitter["Alg::SimpleFitDCHFitter"]
  Alg__SimpleFitTracks["Alg::SimpleFitTracks"]
  Alg__SimpleFitterAlg["Alg::SimpleFitterAlg"]
  Alg__SimpleTrackFitterAlg["Alg::SimpleTrackFitterAlg"]
  Alg__SimpleTracks["Alg::SimpleTracks"]
  Alg__ThreePointTracks["Alg::ThreePointTracks"]
  Alg__TrackStates["Alg::TrackStates"]
  Alg__TrackStates_begin["Alg::TrackStates_begin"]
  Alg__TrackStates_end["Alg::TrackStates_end"]
  Alg__TrackingConf["Alg::TrackingConf"]
  Alg__Tracks["Alg::Tracks"]
  Alg__UseKFPreFit["Alg::UseKFPreFit"]
  Alg___GenFitTracks_trackStates["Alg::_GenFitTracks_trackStates"]
  Alg__dch_deadtime_ns["Alg::dch_deadtime_ns"]
  Alg__dch_drift_um_ns["Alg::dch_drift_um_ns"]
  Alg__dch_gas_type["Alg::dch_gas_type"]
  Alg__dch_sig_mm_ns["Alg::dch_sig_mm_ns"]
  Alg__genfit2["Alg::genfit2"]
  Alg__gf_prefitOutlierVeto["Alg::gf_prefitOutlierVeto"]
  Alg__gf_useKFPreFit["Alg::gf_useKFPreFit"]
  Alg__inputTracks["Alg::inputTracks"]
  Alg__libDCHdigi["Alg::libDCHdigi"]
  Alg__libTracking["Alg::libTracking"]
  Alg__max3DPerTrack["Alg::max3DPerTrack"]
  Alg__minHitsOnTrack["Alg::minHitsOnTrack"]
  Alg__n_states_in_track["Alg::n_states_in_track"]
  Alg__n_tracks["Alg::n_tracks"]
  Alg__n_tracks_evt["Alg::n_tracks_evt"]
  Alg__no_trackstate_prefix["Alg::no_trackstate_prefix"]
  Alg__no_trackstates["Alg::no_trackstates"]
  Alg__nstates_per_track_max["Alg::nstates_per_track_max"]
  Alg__nstates_per_track_med["Alg::nstates_per_track_med"]
  Alg__nstates_per_track_min["Alg::nstates_per_track_min"]
  Alg__outputTracks["Alg::outputTracks"]
  Alg__primary_track_index["Alg::primary_track_index"]
  Alg__primary_track_nstates["Alg::primary_track_nstates"]
  Alg__track["Alg::track"]
  Alg__trackState["Alg::trackState"]
  Alg__trackStates["Alg::trackStates"]
  Alg__trackStates_begin["Alg::trackStates_begin"]
  Alg__trackStates_end["Alg::trackStates_end"]
  Alg__track_collection["Alg::track_collection"]
  Alg__track_index["Alg::track_index"]
  Alg__track_style["Alg::track_style"]
  Alg__tracker["Alg::tracker"]
  Alg__trackerHits_begin["Alg::trackerHits_begin"]
  Alg__trackerHits_end["Alg::trackerHits_end"]
  Alg__view_tracks_metadata["Alg::view_tracks_metadata"]
  Alg__view_tracks_metadata_global["Alg::view_tracks_metadata_global"]
  Archive_SimplerunDCHTestTrackFinder_py["Archive/SimplerunDCHTestTrackFinder.py"]
  Archive_SteeringFile_IDEA_o1_v03_py["Archive/SteeringFile_IDEA_o1_v03.py"]
  Archive_SteeringFile_IDEA_o1_v03DCH_py["Archive/SteeringFile_IDEA_o1_v03DCH.py"]
  Archive_compare_pt_trackstate_vs_hitcircle_py["Archive/compare_pt_trackstate_vs_hitcircle.py"]
  Archive_ddsim_local_sh["Archive/ddsim_local.sh"]
  Archive_filetest_sh["Archive/filetest.sh"]
  Archive_generate_joblist_py["Archive/generate_joblist.py"]
  Archive_local_chain_all_sh["Archive/local_chain_all.sh"]
  Archive_make_ptres_py["Archive/make_ptres.py"]
  Archive_make_sigma_pt_plot_py["Archive/make_sigma_pt_plot.py"]
  Archive_pt_resolution_plot_pyroot_py["Archive/pt_resolution_plot_pyroot.py"]
  Archive_ptres_from_edm4hep_py["Archive/ptres_from_edm4hep.py"]
  Archive_reco_all_sh["Archive/reco_all.sh"]
  Archive_reco_scan_sh["Archive/reco_scan.sh"]
  Archive_run_dch_chain_sh["Archive/run_dch_chain.sh"]
  Archive_simple_local_chain_sh["Archive/simple_local_chain.sh"]
  Archive_skim_edm4hep_py["Archive/skim_edm4hep.py"]
  Archive_test_trackFinder_1_sh["Archive/test_trackFinder_1.sh"]
  Archive_testcondor_sh["Archive/testcondor.sh"]
  W_analysis_1_20_26_1506["W_analysis_1_20_26_1506"]
  cglenn_cc["cglenn.cc"]
  compare_pt_resolution_outputs_py["compare_pt_resolution_outputs.py"]
  dd4hep2root["dd4hep2root"]
  filelist_txt["filelist.txt"]
  local_chain_sh["local_chain.sh"]
  params_job_0_json["params/job_0.json"]
  params_job_1_json["params/job_1.json"]
  params_job_10_json["params/job_10.json"]
  params_job_100_json["params/job_100.json"]
  params_job_101_json["params/job_101.json"]
  params_job_102_json["params/job_102.json"]
  params_job_103_json["params/job_103.json"]
  params_job_104_json["params/job_104.json"]
  params_job_11_json["params/job_11.json"]
  params_job_12_json["params/job_12.json"]
  params_job_13_json["params/job_13.json"]
  params_job_14_json["params/job_14.json"]
  params_job_15_json["params/job_15.json"]
  params_job_16_json["params/job_16.json"]
  params_job_17_json["params/job_17.json"]
  params_job_18_json["params/job_18.json"]
  params_job_19_json["params/job_19.json"]
  params_job_2_json["params/job_2.json"]
  params_job_20_json["params/job_20.json"]
  params_job_21_json["params/job_21.json"]
  params_job_22_json["params/job_22.json"]
  params_job_23_json["params/job_23.json"]
  params_job_24_json["params/job_24.json"]
  params_job_25_json["params/job_25.json"]
  params_job_26_json["params/job_26.json"]
  params_job_27_json["params/job_27.json"]
  params_job_28_json["params/job_28.json"]
  params_job_29_json["params/job_29.json"]
  params_job_3_json["params/job_3.json"]
  params_job_30_json["params/job_30.json"]
  params_job_31_json["params/job_31.json"]
  params_job_32_json["params/job_32.json"]
  params_job_33_json["params/job_33.json"]
  params_job_34_json["params/job_34.json"]
  params_job_35_json["params/job_35.json"]
  params_job_36_json["params/job_36.json"]
  params_job_37_json["params/job_37.json"]
  params_job_38_json["params/job_38.json"]
  params_job_39_json["params/job_39.json"]
  params_job_4_json["params/job_4.json"]
  params_job_40_json["params/job_40.json"]
  params_job_41_json["params/job_41.json"]
  params_job_42_json["params/job_42.json"]
  params_job_43_json["params/job_43.json"]
  params_job_44_json["params/job_44.json"]
  params_job_45_json["params/job_45.json"]
  params_job_46_json["params/job_46.json"]
  params_job_47_json["params/job_47.json"]
  params_job_48_json["params/job_48.json"]
  params_job_49_json["params/job_49.json"]
  params_job_5_json["params/job_5.json"]
  params_job_50_json["params/job_50.json"]
  params_job_51_json["params/job_51.json"]
  params_job_52_json["params/job_52.json"]
  params_job_53_json["params/job_53.json"]
  params_job_54_json["params/job_54.json"]
  params_job_55_json["params/job_55.json"]
  params_job_56_json["params/job_56.json"]
  params_job_57_json["params/job_57.json"]
  params_job_58_json["params/job_58.json"]
  params_job_59_json["params/job_59.json"]
  params_job_6_json["params/job_6.json"]
  params_job_60_json["params/job_60.json"]
  params_job_61_json["params/job_61.json"]
  params_job_62_json["params/job_62.json"]
  params_job_63_json["params/job_63.json"]
  params_job_64_json["params/job_64.json"]
  params_job_65_json["params/job_65.json"]
  params_job_66_json["params/job_66.json"]
  params_job_67_json["params/job_67.json"]
  params_job_68_json["params/job_68.json"]
  params_job_69_json["params/job_69.json"]
  params_job_7_json["params/job_7.json"]
  params_job_70_json["params/job_70.json"]
  params_job_71_json["params/job_71.json"]
  params_job_72_json["params/job_72.json"]
  params_job_73_json["params/job_73.json"]
  params_job_74_json["params/job_74.json"]
  params_job_75_json["params/job_75.json"]
  params_job_76_json["params/job_76.json"]
  params_job_77_json["params/job_77.json"]
  params_job_78_json["params/job_78.json"]
  params_job_79_json["params/job_79.json"]
  params_job_8_json["params/job_8.json"]
  params_job_80_json["params/job_80.json"]
  params_job_81_json["params/job_81.json"]
  params_job_82_json["params/job_82.json"]
  params_job_83_json["params/job_83.json"]
  params_job_84_json["params/job_84.json"]
  params_job_85_json["params/job_85.json"]
  params_job_86_json["params/job_86.json"]
  params_job_87_json["params/job_87.json"]
  params_job_88_json["params/job_88.json"]
  params_job_89_json["params/job_89.json"]
  params_job_9_json["params/job_9.json"]
  params_job_90_json["params/job_90.json"]
  params_job_91_json["params/job_91.json"]
  params_job_92_json["params/job_92.json"]
  params_job_93_json["params/job_93.json"]
  params_job_94_json["params/job_94.json"]
  params_job_95_json["params/job_95.json"]
  params_job_96_json["params/job_96.json"]
  params_job_97_json["params/job_97.json"]
  params_job_98_json["params/job_98.json"]
  params_job_99_json["params/job_99.json"]
  runDCHTestTrackFinder_py["runDCHTestTrackFinder.py"]
  runTestTrackFinder_py["runTestTrackFinder.py"]
  scripts_analyze_pt_resolution_grid_py["scripts/analyze_pt_resolution_grid.py"]
  scripts_autoreadme_py["scripts/autoreadme.py"]
  scripts_cglenn_cc["scripts/cglenn.cc"]
  scripts_compact_path_txt["scripts/compact_path.txt"]
  scripts_compare_pt_resolution_grid_py["scripts/compare_pt_resolution_grid.py"]
  scripts_condor_ddsim_sh["scripts/condor_ddsim.sh"]
  scripts_condor_reco_sh["scripts/condor_reco.sh"]
  scripts_debug_z_spur_event_py["scripts/debug_z_spur_event.py"]
  scripts_dump_covmatrix_one_event_py["scripts/dump_covmatrix_one_event.py"]
  scripts_filelist_txt["scripts/filelist.txt"]
  scripts_inspect_events_pt_pathology_py["scripts/inspect_events_pt_pathology.py"]
  scripts_make_filelist_sh["scripts/make_filelist.sh"]
  scripts_make_runtime_sh["scripts/make_runtime.sh"]
  scripts_mk_ddsim_grid_py["scripts/mk_ddsim_grid.py"]
  scripts_plot_mcparticles_pt_py["scripts/plot_mcparticles_pt.py"]
  scripts_prepare_and_submit_sh["scripts/prepare_and_submit.sh"]
  scripts_print_metadata_py["scripts/print_metadata.py"]
  scripts_queue_items_txt["scripts/queue_items.txt"]
  scripts_reco_job_sh["scripts/reco_job.sh"]
  scripts_scan_pt_time_by_event_py["scripts/scan_pt_time_by_event.py"]
  scripts_stamp_ddsim_metadata_py["scripts/stamp_ddsim_metadata.py"]
  scripts_stamp_pipeline_metadata_py["scripts/stamp_pipeline_metadata.py"]
  scripts_submit_reco_sh["scripts/submit_reco.sh"]
  scripts_sweep_pt_sh["scripts/sweep_pt.sh"]
  scripts_view_simhits_event_py["scripts/view_simhits_event.py"]
  scripts_view_tracks_event_py["scripts/view_tracks_event.py"]
  test_trackFinder_sh["test_trackFinder.sh"]
  view_tracks_event_simhits_py["view_tracks_event_simhits.py"]
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__CDCHTracks
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__DCHCollection
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__DCH_DigiCollection
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__DCH_v2
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__DCHdigi
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__GGTF_tracking
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__GenFit2DCHFitter
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__GenFitFieldSvc
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__GenFitMaterialSvc
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__GenFitTracks
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__RetryIfNoFitterInfo
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__genfit2
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__max3DPerTrack
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__minHitsOnTrack
  Archive_SimplerunDCHTestTrackFinder_py --> Alg__outputTracks
  Archive_SteeringFile_IDEA_o1_v03_py --> Alg__Geant4TestTrackAction
  Archive_SteeringFile_IDEA_o1_v03_py --> Alg__Geant4TrackerWeightedAction
  Archive_SteeringFile_IDEA_o1_v03_py --> Alg__tracker
  Archive_SteeringFile_IDEA_o1_v03DCH_py --> Alg__DCH_ID_Encoding
  Archive_SteeringFile_IDEA_o1_v03DCH_py --> Alg__DCH_v2
  Archive_SteeringFile_IDEA_o1_v03DCH_py --> Alg__Geant4SimpleTrackerAction
  Archive_SteeringFile_IDEA_o1_v03DCH_py --> Alg__Geant4TrackerWeightedAction
  Archive_SteeringFile_IDEA_o1_v03DCH_py --> Alg__tracker
  Archive_compare_pt_trackstate_vs_hitcircle_py --> Alg__GenFitTracks
  Archive_compare_pt_trackstate_vs_hitcircle_py --> Alg__TrackStates_begin
  Archive_compare_pt_trackstate_vs_hitcircle_py --> Alg__TrackStates_end
  Archive_compare_pt_trackstate_vs_hitcircle_py --> Alg__trackStates_begin
  Archive_compare_pt_trackstate_vs_hitcircle_py --> Alg__trackStates_end
  Archive_compare_pt_trackstate_vs_hitcircle_py --> Archive_compare_pt_trackstate_vs_hitcircle_py
  Archive_filetest_sh --> Alg__GenFitTracks_trackStates_
  Archive_filetest_sh --> Alg__GenFitTracks_trackStates_omega
  Archive_filetest_sh --> Alg__GenFitTracks_trackStates_phi
  Archive_filetest_sh --> Alg__GenFitTracks_trackStates_qOverP
  Archive_filetest_sh --> Alg__GenFitTracks_trackStates_tanLambda
  Archive_filetest_sh --> Alg__GenFitTracks_trackStates_theta
  Archive_filetest_sh --> Alg__GenFitTracks_tracks_omega
  Archive_filetest_sh --> Alg__GenFitTracks_tracks_qOverP
  Archive_filetest_sh --> Alg__GenFitTracks_tracks_theta
  Archive_filetest_sh --> Alg___GenFitTracks_trackStates
  Archive_make_ptres_py --> Alg__CDCHTracks
  Archive_make_ptres_py --> Alg__GenFitTracks
  Archive_make_ptres_py --> Alg__SimpleFitTracks
  Archive_make_ptres_py --> Alg__SimpleTracks
  Archive_make_ptres_py --> Alg__ThreePointTracks
  Archive_make_ptres_py --> Alg__Tracks
  Archive_make_ptres_py --> Alg__genfit2
  Archive_make_sigma_pt_plot_py --> Alg__GenFitTracks
  Archive_pt_resolution_plot_pyroot_py --> Alg__GenFitTracks
  Archive_ptres_from_edm4hep_py --> Alg__GenFitTracks
  Archive_ptres_from_edm4hep_py --> Alg__n_tracks
  Archive_reco_all_sh --> Alg__genfit2
  Archive_reco_scan_sh --> Alg__genfit2
  Archive_reco_scan_sh --> runDCHTestTrackFinder_py
  Archive_simple_local_chain_sh --> Alg__DCHCollection
  Archive_simple_local_chain_sh --> Alg__DCH_v2
  Archive_simple_local_chain_sh --> Archive_SimplerunDCHTestTrackFinder_py
  Archive_skim_edm4hep_py --> Alg__DCHCollection
  local_chain_sh --> Alg__DCHCollection
  local_chain_sh --> Alg__DCH_v2
  local_chain_sh --> Alg__GenFitTracks
  local_chain_sh --> Alg__Tracks
  local_chain_sh --> runDCHTestTrackFinder_py
  runDCHTestTrackFinder_py --> Alg__CDCHTracks
  runDCHTestTrackFinder_py --> Alg__DCHCollection
  runDCHTestTrackFinder_py --> Alg__DCHDigi2Collection
  runDCHTestTrackFinder_py --> Alg__DCHDigi2SimLink
  runDCHTestTrackFinder_py --> Alg__DCHDigi2SimLinkCollection
  runDCHTestTrackFinder_py --> Alg__DCHDigiSimLink
  runDCHTestTrackFinder_py --> Alg__DCHDigiSimLinkCollection
  runDCHTestTrackFinder_py --> Alg__DCHName
  runDCHTestTrackFinder_py --> Alg__DCHSimHits
  runDCHTestTrackFinder_py --> Alg__DCH_DigiCollection
  runDCHTestTrackFinder_py --> Alg__DCH_name
  runDCHTestTrackFinder_py --> Alg__DCH_simhits
  runDCHTestTrackFinder_py --> Alg__DCH_v2
  runDCHTestTrackFinder_py --> Alg__DCHdigiConf
  runDCHTestTrackFinder_py --> Alg__DCHdigi_v01
  runDCHTestTrackFinder_py --> Alg__DCHdigi_v02
  runDCHTestTrackFinder_py --> Alg__DchName
  runDCHTestTrackFinder_py --> Alg__DiagEveryNTracks
  runDCHTestTrackFinder_py --> Alg__GGTF_tracking
  runDCHTestTrackFinder_py --> Alg__GenFit2DCHFitter
  runDCHTestTrackFinder_py --> Alg__GenFit2DCHFitter_props
  runDCHTestTrackFinder_py --> Alg__GenFitFieldSvc
  runDCHTestTrackFinder_py --> Alg__GenFitMaterialSvc
  runDCHTestTrackFinder_py --> Alg__GenFitTracks
  runDCHTestTrackFinder_py --> Alg__InputTracks
  runDCHTestTrackFinder_py --> Alg__MinFittedPointsWithFI
  runDCHTestTrackFinder_py --> Alg__MinHitsPerTrack
  runDCHTestTrackFinder_py --> Alg__MinMeasurementsToFit
  runDCHTestTrackFinder_py --> Alg__OutputTracks
  runDCHTestTrackFinder_py --> Alg__OutputTracksGGTF
  runDCHTestTrackFinder_py --> Alg__PreFitOutlierVeto
  runDCHTestTrackFinder_py --> Alg__TrackingConf
  runDCHTestTrackFinder_py --> Alg__UseKFPreFit
  runDCHTestTrackFinder_py --> Alg__dch_deadtime_ns
  runDCHTestTrackFinder_py --> Alg__dch_drift_um_ns
  runDCHTestTrackFinder_py --> Alg__dch_gas_type
  runDCHTestTrackFinder_py --> Alg__dch_sig_mm_ns
  runDCHTestTrackFinder_py --> Alg__genfit2
  runDCHTestTrackFinder_py --> Alg__gf_prefitOutlierVeto
  runDCHTestTrackFinder_py --> Alg__gf_useKFPreFit
  runDCHTestTrackFinder_py --> Alg__inputTracks
  runDCHTestTrackFinder_py --> Alg__outputTracks
  runTestTrackFinder_py --> Alg__CDCHTracks
  runTestTrackFinder_py --> Alg__DCHCollection
  runTestTrackFinder_py --> Alg__DCH_DigiCollection
  runTestTrackFinder_py --> Alg__DCH_v2
  runTestTrackFinder_py --> Alg__DCHdigi
  runTestTrackFinder_py --> Alg__GGTF_tracking
  scripts_analyze_pt_resolution_grid_py --> Alg__GenFitTracks
  scripts_autoreadme_py --> ___
  scripts_autoreadme_py --> Alg__track
  scripts_compare_pt_resolution_grid_py --> compare_pt_resolution_outputs_py
  scripts_condor_reco_sh --> Alg__genfit2
  scripts_condor_reco_sh --> runDCHTestTrackFinder_py
  scripts_debug_z_spur_event_py --> Alg__DCHDigi2Collection
  scripts_debug_z_spur_event_py --> Alg__DCHDigi2SimLinkCollection
  scripts_debug_z_spur_event_py --> Alg__DCHDigiCollection
  scripts_debug_z_spur_event_py --> Alg__DCHDigiSimLinkCollection
  scripts_debug_z_spur_event_py --> Alg__DCH_DigiCollection
  scripts_dump_covmatrix_one_event_py --> scripts_dump_covmatrix_one_event_py
  scripts_inspect_events_pt_pathology_py --> Alg__GenFitTracks
  scripts_make_runtime_sh --> Alg__GenFit2DCHFitter
  scripts_make_runtime_sh --> Alg__HelixFitter
  scripts_make_runtime_sh --> Alg__SimpleFitDCHFitter
  scripts_make_runtime_sh --> Alg__SimpleFitterAlg
  scripts_make_runtime_sh --> Alg__SimpleTrackFitterAlg
  scripts_make_runtime_sh --> Alg__TrackingConf
  scripts_make_runtime_sh --> Alg__libDCHdigi
  scripts_make_runtime_sh --> Alg__libTracking
  scripts_plot_mcparticles_pt_py --> Alg__GenFit
  scripts_plot_mcparticles_pt_py --> Alg__GenFitTracks
  scripts_plot_mcparticles_pt_py --> Alg__TrackStates
  scripts_plot_mcparticles_pt_py --> Alg__trackState
  scripts_plot_mcparticles_pt_py --> Alg__trackStates
  scripts_prepare_and_submit_sh --> scripts_mk_ddsim_grid_py
  scripts_reco_job_sh --> Alg__DCHCollection
  scripts_reco_job_sh --> Alg__DCH_v2
  scripts_reco_job_sh --> Alg__GenFitTracks
  scripts_reco_job_sh --> Alg__Tracks
  scripts_scan_pt_time_by_event_py --> Alg__GenFitTracks
  scripts_scan_pt_time_by_event_py --> Alg__TrackStates_begin
  scripts_scan_pt_time_by_event_py --> Alg__TrackStates_end
  scripts_scan_pt_time_by_event_py --> Alg__n_tracks_evt
  scripts_scan_pt_time_by_event_py --> Alg__nstates_per_track_max
  scripts_scan_pt_time_by_event_py --> Alg__nstates_per_track_med
  scripts_scan_pt_time_by_event_py --> Alg__nstates_per_track_min
  scripts_scan_pt_time_by_event_py --> Alg__primary_track_index
  scripts_scan_pt_time_by_event_py --> Alg__primary_track_nstates
  scripts_scan_pt_time_by_event_py --> Alg__trackStates_begin
  scripts_scan_pt_time_by_event_py --> Alg__trackStates_end
  scripts_scan_pt_time_by_event_py --> Alg__trackerHits_begin
  scripts_scan_pt_time_by_event_py --> Alg__trackerHits_end
  scripts_scan_pt_time_by_event_py --> scripts_scan_pt_time_by_event_py
  scripts_submit_reco_sh --> scripts_make_filelist_sh
  scripts_sweep_pt_sh --> local_chain_sh
  scripts_view_simhits_event_py --> Alg__DCHCollection
  scripts_view_simhits_event_py --> Alg__GenFitTracks
  scripts_view_simhits_event_py --> Alg__TrackStates_begin
  scripts_view_simhits_event_py --> Alg__TrackStates_end
  scripts_view_simhits_event_py --> Alg__n_states_in_track
  scripts_view_simhits_event_py --> Alg__no_trackstate_prefix
  scripts_view_simhits_event_py --> Alg__no_trackstates
  scripts_view_simhits_event_py --> Alg__trackStates_begin
  scripts_view_simhits_event_py --> Alg__trackStates_end
  scripts_view_simhits_event_py --> Alg__track_collection
  scripts_view_simhits_event_py --> Alg__track_index
  scripts_view_simhits_event_py --> Alg__track_style
  scripts_view_simhits_event_py --> Alg__view_tracks_metadata
  scripts_view_simhits_event_py --> Alg__view_tracks_metadata_global
  scripts_view_simhits_event_py --> view_tracks_event_simhits_py
  scripts_view_tracks_event_py --> Alg__DCHDigi2Collection
  scripts_view_tracks_event_py --> Alg__GenFitTracks
  scripts_view_tracks_event_py --> Alg__TrackStates_begin
  scripts_view_tracks_event_py --> Alg__TrackStates_end
  scripts_view_tracks_event_py --> Alg__n_states_in_track
  scripts_view_tracks_event_py --> Alg__trackStates_begin
  scripts_view_tracks_event_py --> Alg__trackStates_end
  scripts_view_tracks_event_py --> Alg__track_collection
  scripts_view_tracks_event_py --> Alg__track_index
  scripts_view_tracks_event_py --> Alg__track_style
  scripts_view_tracks_event_py --> Alg__view_tracks_metadata
  scripts_view_tracks_event_py --> scripts_view_tracks_event_py
